update-ssh-job:
  stage: deploy
  image: alpine
  before_script:
    - apk add git
    - apk add openssh
    - apk add --no-cache lftp
    - apk add sshpass
    - apk add lftp
  script:
    - mkdir /root/.ssh                                # Create .ssh directory
    - chmod 700 /root/.ssh                            # Set permissions
    - touch /root/.ssh/known_hosts                    # Create known_hosts files
    - chmod 600 /root/.ssh/known_hosts                # Set permissions
    - ssh-keyscan -H hem.ssis.nu >> /root/.ssh/known_hosts  # Add server to known_hosts
    - echo "Debug - Listing."
    - ls
    - echo "Starting to push website to hem.ssis.nu..."
    - echo "Uploading to server..."
    - lftp -e "mirror -e -P 4 -R --transfer-all --reverse -X .gitignore -X .gitlab-ci.yml -X .vscode/ -X .git/ . /public_html/portfolio/ --verbose; quit" -u "$SFTP_USERNAME,$SFTP_PASSWORD" sftp://hem.ssis.nu -p 22
    - echo "Uploaded to server."
  timeout: 2min