update-ssh-job:
  stage: deploy
  image: alpine
  script:
    - echo "Debug - Listing."
    - ls
    - echo "Starting to push website to hem.ssis.nu..."
    - apk add sshpass
    - apk add lftp
    - echo "Uploading to server..."
    - lftp -e -P 4 "open hem.ssis.nu; user 20alse $SFTP_PASSWORD; mirror -R . /public_html/portfolio/ --reverse --verbose; bye"
    - echo "Uploaded to server."
  timeout: 5min