variables:
  SFTP_PASSWORD: $SFTP_PASSWORD
update-ssh-job:
  stage: deploy
  image: alpine
  script:
    - echo "Debug - Listing."
    - ls
    - echo "Starting to push website to hem.ssis.nu..."
    - apk add sshpass
    - apk add lftp
    - echo "Uploading to server..."
    #- sshpass -p $SFTP_PASSWORD sftp 20alse@hem.ssis.nu:/portfolio .
    - lftp -e "open hem.ssis.nu; user 20alse; password $SFTP_PASSWORD; mirror -X .* -X ./portfolio/*/ --reverse --verbose; bye"
    - echo "Uploaded to server."