variables:
  SFTP_PASSWORD: $SFTP_PASSWORD
update-ssh-job:
  stage: deploy
  image: alpine
  script:
    - echo "Debug - Listing."
    - ls
    - echo "Starting to push website to hem.ssis.nu..."
    - apt install sshpass
    - echo "Uploading to server..."
    - sshpass -p $SFTP_PASSWORD sftp 20alse@hem.ssis.nu:/portfolio /portfolio
    - echo "Uploaded to server."